blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/srivilliamsai/resume-ecosystem-node/discussions
    about: Ask questions and discuss ideas with the community.
